volumes:
  django_static:
  postgres_data:


x-python: &python
  build: .
  restart: unless-stopped
  user: 10000:10000
  read_only: true
  env_file: .env
  tmpfs:
    - /tmp
  volumes:
    - django_static:/app/static_root/:rw


services:
  django:
    <<: *python
    environment:
      SITE_ID: 1
      DOMAIN: localhost
    command: "./manage.py runserver 0.0.0.0:8000"

  celery:
    <<: *python
    command:
      - /bin/bash
      - -c
      - |
         python3 manage.py migrate
         python3 manage.py collectstatic --noinput
         celery -A config worker -c 3 -B --loglevel=info -E

  nginx:
    image: docker.io/snakesoft/djanginx:1.0
    restart: unless-stopped
    volumes:
      - django_static:/app/static_root/:ro
    ports:
      - "${SITE_1_PORT}:80"
    environment:
      LISTEN_DOMAIN: ${SITE_1_DOMAIN}
      SITE_HOSTNAME: django

  redis:
    image: redis/redis-stack-server:7.4.0-v1
    restart: unless-stopped

  postgres:
    image: postgres:17.2-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
